# Lab 3: Project Jump Start (Worksheet)

**Name:**

**Learning Objectives:**

- Using `try` and `except` to create a safe type-casting module. (Code)
- Reading/writing data files using `pandas`. (Code)
- Manipulating data using lists and dictionaries. (Code)
- Develop a complex algorithm by breaking the task down into simple steps. (Code)

In this lab, we will compute one of the metrics discussed in last class, which is for each term, room and day of week, what is the proportion of "prime time" (from say 10 to 16) that is utilized. 

# Module 1: Applying String Splitting and Casting 

Recall the functions for converting a string into an integer and for splitting strings from last time
```python
'hello world'.split(' ')
int('54')
```

When we type 
```python
int('fasdf')
```
There will be an error and the code crashes. To prevent the crash, we use the `try` and `except` construct:

```python
inputData='fasdf'

try:
    output=int(inputData)
except:
    output='Not a number'
print(output)
```
Type out the above code yourself and see.

**Exercise 1:**
Write a function `convert(inputNum)` that converts a given inputNum into an int, and return `np.nan` (not a number) if there's an error.

In [3]:
try:
    output = int('3.5')
except:
    output = 'Not a Number'
    
print(output)

Not a Number

In [6]:
import numpy as np
def convert(inputNum):
    try:
        output=int(inputNum)
    except:
        output='nan'
    return(output)
    # Insert your code here inside the function.
    
print(convert('3'))      # should return 3
print(convert('fadsf'))  # should return np.nan
print(convert('1.5'))    # should also return np.nan, because 1.5 is fractional and not an integer

3
nan
nan

In [2]:
# Expected output

3
nan
nan

## Challenge 1
**Part a:** Correctly convert the following input into the number of hours since midnight and set it to the variable output. Then replace inputTime with `inputTime='3f'` and see if you get `nan` as output.

In [16]:
inputTime='14:25:33'
try:
    hrs,mins,secs = inputTime.split(':')
    output = int(hrs)+int(mins)/60.0+ int(secs)/3600.0
    print(output)
except:
    output = 'not time'
    print(output)

# Complete your code here

14.425833333333333

In [4]:
# Expected output

14.425833333333333

**Part b:** Write your working code from above into a function called `convert`, which takes an input string and convert it to a `float` representing hours since midnight if possible, otherwise returns `np.nan`.

In [21]:

import numpy as np

def convert(inputTime):
    try:
        hrs,mins,secs = inputTime.split(':')
        output = int(hrs)+int(mins)/60.0+ int(secs)/3600.0
        return(output)
    except:
        output = np.nan
        return(output)
    pass
print(convert('20:30:00'))
print(convert('TBA'))
print(convert(np.nan))

20.5
nan
nan

In [6]:
# Expected output

20.5
nan
nan

# Demonstration of Loading Data with Pandas (More Next Class)

To run the following code, you must either copy the three excel files below (from the Final Project zip file) into the same folder as the present Jupyter notebook, or change the directory below to point to the file.

In [22]:
import pandas as pd
schedule=pd.read_excel('Marshall_Course_Enrollment_1516_1617.xlsx')
cancelled=pd.read_excel('Cancelled_Courses_1516_1617.xlsx')
master=schedule.append(cancelled)
capacities=pd.read_excel('Marshall_Room_Capacity_Chart.xlsx')

master.info()

master.to_csv('Merged_Enrollment.csv')
master.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6131 entries, 0 to 3231
Data columns (total 26 columns):
Course                   3363 non-null object
Course Prefix            6131 non-null object
Course Suffix            6131 non-null object
Department               3363 non-null object
First Begin Time         5629 non-null object
First Days               5553 non-null object
First End Time           5629 non-null object
First Instructor         5664 non-null object
First Instructor UID     5645 non-null float64
First Room               5696 non-null object
Link                     936 non-null object
Max Units                6131 non-null float64
Min Units                6131 non-null float64
Mode                     6131 non-null object
Reg Count                6131 non-null int64
Seats                    6131 non-null int64
Second Begin Time        43 non-null object
Second Days              43 non-null object
Second End Time          43 non-null object
Second Instructor        595 non-null object
Second Instructor UID    595 non-null float64
Second Room              19 non-null object
Section                  6131 non-null int64
Session                  6131 non-null int64
Term                     6131 non-null int64
Title                    6131 non-null object
dtypes: float64(4), int64(5), object(17)
memory usage: 1.3+ MB

,Course,Course Prefix,Course Suffix,Department,First Begin Time,First Days,First End Time,First Instructor,First Instructor UID,First Room,...,Second Begin Time,Second Days,Second End Time,Second Instructor,Second Instructor UID,Second Room,Section,Session,Term,Title
0,ACCT-370,ACCT,370,ACCT,10:00:00,F,11:50:00,"Hopkins, Merle, W",3.783354e+09,SLH200,...,NaN,NaN,NaN,NaN,NaN,NaN,14029,1,20153,External Financial Reporting Issues
1,ACCT-370,ACCT,370,ACCT,08:00:00,MW,09:50:00,"Hopkins, Merle, W",3.783354e+09,ACC303,...,NaN,NaN,NaN,NaN,NaN,NaN,14025,1,20153,External Financial Reporting Issues
2,ACCT-370,ACCT,370,ACCT,10:00:00,MW,11:50:00,"Hopkins, Merle, W",3.783354e+09,ACC303,...,NaN,NaN,NaN,NaN,NaN,NaN,14026,1,20153,External Financial Reporting Issues
3,ACCT-370,ACCT,370,ACCT,12:00:00,MW,13:50:00,"Hopkins, Merle, W",3.783354e+09,ACC303,...,NaN,NaN,NaN,NaN,NaN,NaN,14027,1,20153,External Financial Reporting Issues
4,ACCT-371,ACCT,371,ACCT,10:00:00,F,11:50:00,NaN,NaN,SLH200,...,NaN,NaN,NaN,NaN,NaN,NaN,14044,1,20153,Introduction to Accounting Systems

In [8]:
# Expected output from the above code

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6131 entries, 0 to 3231
Data columns (total 26 columns):
Course                   3363 non-null object
Course Prefix            6131 non-null object
Course Suffix            6131 non-null object
Department               3363 non-null object
First Begin Time         5629 non-null object
First Days               5553 non-null object
First End Time           5629 non-null object
First Instructor         5664 non-null object
First Instructor UID     5645 non-null float64
First Room               5696 non-null object
Link                     936 non-null object
Max Units                6131 non-null float64
Min Units                6131 non-null float64
Mode                     6131 non-null object
Reg Count                6131 non-null int64
Seats                    6131 non-null int64
Second Begin Time        43 non-null object
Second Days              43 non-null object
Second End Time          43 non-null object
Second Instructor        595 non-null object
Second Instructor UID    595 non-null float64
Second Room              19 non-null object
Section                  6131 non-null int64
Session                  6131 non-null int64
Term                     6131 non-null int64
Title                    6131 non-null object
dtypes: float64(4), int64(5), object(17)
memory usage: 1.3+ MB

,Course,Course Prefix,Course Suffix,Department,First Begin Time,First Days,First End Time,First Instructor,First Instructor UID,First Room,...,Second Begin Time,Second Days,Second End Time,Second Instructor,Second Instructor UID,Second Room,Section,Session,Term,Title
0,ACCT-370,ACCT,370,ACCT,10:00:00,F,11:50:00,"Hopkins, Merle, W",3.783354e+09,SLH200,...,NaN,NaN,NaN,NaN,NaN,NaN,14029,1,20153,External Financial Reporting Issues
1,ACCT-370,ACCT,370,ACCT,08:00:00,MW,09:50:00,"Hopkins, Merle, W",3.783354e+09,ACC303,...,NaN,NaN,NaN,NaN,NaN,NaN,14025,1,20153,External Financial Reporting Issues
2,ACCT-370,ACCT,370,ACCT,10:00:00,MW,11:50:00,"Hopkins, Merle, W",3.783354e+09,ACC303,...,NaN,NaN,NaN,NaN,NaN,NaN,14026,1,20153,External Financial Reporting Issues
3,ACCT-370,ACCT,370,ACCT,12:00:00,MW,13:50:00,"Hopkins, Merle, W",3.783354e+09,ACC303,...,NaN,NaN,NaN,NaN,NaN,NaN,14027,1,20153,External Financial Reporting Issues
4,ACCT-371,ACCT,371,ACCT,10:00:00,F,11:50:00,NaN,NaN,SLH200,...,NaN,NaN,NaN,NaN,NaN,NaN,14044,1,20153,Introduction to Accounting Systems

## Module 2: Using Dictionaries and Sets

This module gives us practice on using fundamental Python data structures called dictionaries and sets. The challenge code allows us to separate out for each term, classroom, and day the set of time slots that the room is used. 

Recall that a list produces a mapping from a position index to a value. We can retrive the value by position, and append to the list as below.
```python
l=[1,3,5]
l[1]
l.append(6)
```

A dictionary is a mapping that allows for more complex indices. We can add to it by simply using indexing. 
```python
d={'apple':3,5:'five','orange':9}
d['apple']
d['Jack']='a friend'
```

We can test if something is in a dictionary as with a list
```python
'apple' in d
'apple' not in d
```

**Exercse 2:**
Define a dictionary mapping between `[1,3,5]` and 2 times of the numbers. Print the dictionary. Print whether 5 and '5' are in the dictionary. Then replace the value for 5 with 'Ten' and set the value for 'Six' to be 'Twelve'. Print the dictionary again.

In [34]:
dict = {1:2,3:6,5:10}
print(dict)
print(5 in dict)
print('5' in dict)
dict[5]='Ten'
print(dict)
dict['Six']='Twelve'
print(dict)

{1: 2, 3: 6, 5: 10}
True
False
{1: 2, 3: 6, 5: 'Ten'}
{1: 2, 3: 6, 5: 'Ten', 'Six': 'Twelve'}

In [36]:
for key in dict:
    print('Key = {0}, Value = {1}'.format(key,dict[key]))

Key = 1, Value = 2
Key = 3, Value = 6
Key = 5, Value = Ten
Key = Six, Value = Twelve

We can iterate through a dictionary as follows
```python
for key in d:
    print('Key={0} Value={1}'.format(key,d[key]))
```

**Exercise 3**:
Create a new dictionary and give it arbitrary mappings, then use the above code to print how line by line the key to value correspondence of a new dictionary that you create.

In [38]:
d={i:i*i for i in [3,4,5]}
print(d)

{3: 9, 4: 16, 5: 25}

Just as with list comprehension, we can create a dictionary as follows.
```
{i:i*i for i in [3,4,5]}
```

**Exercise 4**:
Create a dictionary that maps every number in range(6) to a string value: `{0:'0',1:'1',...}`. Do this two ways, first using a for loop and additing to an empty dictionary `{}`. Second, use the notation above.

In [40]:
d={}
for i in range(6):
    d[i] = str(i)
print(d)

{0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5'}

In [12]:
# Expected output

{0: '0', 1: '1', 2: '2', 3: '3', 4: '4'}

## Sets

Sets is another construct like list, except that every element can only occur once in the set. 
```
s={3,5,6}
print(s)
s=set([3,3,4,5])
print(s)
```
Try typing the above and execute.

You can check for set membership or iterate through a set as with dictionaries. The benefit of sets over lists is that checking for membership is much faster, and elements are guaranteed to be unique.

```python
3 in s
3 not in s
for element in s:
    print(element)
len(s)
s.add('three')
```

**Exercise:**
Given the list `['a','b','a','a','c']`, obtain the number of unique elements by changing it into a set and querying for the length. Then check whether `'d'` is in the set. Finally, add 'd' to the set and check again.

In [53]:
l=['a','b','a','a','c']
setl = set(l)
lenOfL=len(set(l))
print('# of unique elements is {}'.format(lenOfL))
print('d' in setl)
setl.add('d')
print(setl)
print('d' in setl)

# of unique elements is 3
False
{'a', 'b', 'c', 'd'}
True

In [16]:
# Expected output

{'a', 'c', 'b'}
Number of unique elements is 3
False
True


## Challenge 2:
Load the data from the master file and put it into a dictionary with keys (term,room,day), filtering only for the rooms that are in the capacity file, as well as the rows with valid first begin times. The value of each entry should be a tuple of the earliest begin time found and the latest end time found.

In [17]:
#Importing packages
import pandas as pd
import numpy as np

#Reading excel files
master=pd.read_csv('Merged_Enrollment.csv')
capacities=pd.read_excel('Marshall_Room_Capacity_Chart.xlsx')

roomSet=set(capacities.Room)
ans={}

df=master

In [ ]:
for index,row in df.iterrows():
    # Complete your code here.
    term=row['Term']
    room=row['First Room']
    days=row['First Days'] 
    beg = row['First Begin Time']
    end=row['First End Time']
    
    # ADD CODE HERE to obtain the 'First Begin Time' and try to change to a integer beg.
    # ADD CODE HERE to obtain the 'First End Time' and try to change to a integer end.
    if np.isnan(beg1) or np.isnan(end1) or room not in roomSet:
        continue
    for day in 'MTWHF':
        if day in days: 
            key=(term,room,day)
            if key not in ans:
                ans[key] = (beg,end)# ADD CODE HERE to input (beg,end) into the dictionary ans[key]
            else:
                oldbeg,oldend = ans[key]
                newBeg = 
                # ADD CODE HERE to update ans[key] to have the earliest begin time found and latest end time found.
                
            
ans

In [18]:
# Expected output

{(20153, 'ACC201', 'F'): (11.0, 14.333333333333334),
 (20153, 'ACC201', 'H'): (10.0, 19.833333333333332),
 (20153, 'ACC201', 'M'): (8.0, 19.833333333333332),
 (20153, 'ACC201', 'T'): (10.0, 19.833333333333332),
 (20153, 'ACC201', 'W'): (8.0, 19.833333333333332),
 (20153, 'ACC205', 'F'): (11.5, 14.833333333333334),
 (20153, 'ACC205', 'H'): (10.0, 20.333333333333332),
 (20153, 'ACC205', 'M'): (10.0, 21.5),
 (20153, 'ACC205', 'T'): (10.0, 20.333333333333332),
 (20153, 'ACC205', 'W'): (10.0, 20.833333333333332),
 (20153, 'ACC236', 'H'): (8.0, 21.5),
 (20153, 'ACC236', 'M'): (10.0, 21.5),
 (20153, 'ACC236', 'T'): (8.0, 21.5),
 (20153, 'ACC236', 'W'): (10.0, 21.5),
 (20153, 'ACC303', 'F'): (8.5, 15.833333333333334),
 (20153, 'ACC303', 'H'): (8.0, 21.833333333333332),
 (20153, 'ACC303', 'M'): (8.0, 19.833333333333332),
 (20153, 'ACC303', 'T'): (8.0, 21.5),
 (20153, 'ACC303', 'W'): (8.0, 19.833333333333332),
 (20153, 'ACC310', 'H'): (8.0, 17.833333333333332),
 (20153, 'ACC310', 'M'): (8.0, 21.5),
 (20153, 'ACC310', 'T'): (8.0, 17.833333333333332),
 (20153, 'ACC310', 'W'): (8.0, 17.833333333333332),
 (20153, 'ACC312', 'F'): (13.0, 15.833333333333334),
 (20153, 'ACC312', 'H'): (12.0, 17.833333333333332),
 (20153, 'ACC312', 'M'): (9.0, 11.833333333333334),
 (20153, 'ACC312', 'T'): (12.0, 17.833333333333332),
 (20153, 'ACC312', 'W'): (9.5, 16.833333333333332),
 (20153, 'BRI202', 'F'): (13.0, 16.0),
 (20153, 'BRI202', 'H'): (12.5, 15.333333333333334),
 (20153, 'BRI202', 'M'): (9.5, 21.5),
 (20153, 'BRI202', 'T'): (12.5, 21.5),
 (20153, 'BRI202', 'W'): (9.5, 20.0),
 (20153, 'BRI202A', 'H'): (8.0, 17.833333333333332),
 (20153, 'BRI202A', 'M'): (8.0, 19.833333333333332),
 (20153, 'BRI202A', 'T'): (8.0, 19.833333333333332),
 (20153, 'BRI202A', 'W'): (8.0, 19.833333333333332),
 (20153, 'BRI5', 'F'): (8.0, 18.0),
 (20153, 'BRI5', 'H'): (10.0, 21.166666666666668),
 (20153, 'BRI5', 'M'): (10.0, 20.833333333333332),
 (20153, 'BRI5', 'T'): (10.0, 20.833333333333332),
 (20153, 'BRI5', 'W'): (8.0, 21.5),
 (20153, 'BRI8', 'F'): (8.0, 15.833333333333334),
 (20153, 'BRI8', 'H'): (8.0, 19.833333333333332),
 (20153, 'BRI8', 'M'): (8.0, 19.833333333333332),
 (20153, 'BRI8', 'T'): (8.0, 19.833333333333332),
 (20153, 'BRI8', 'W'): (8.0, 19.833333333333332),
 (20153, 'HOH EDI', 'F'): (10.0, 15.833333333333334),
 (20153, 'HOH EDI', 'H'): (8.0, 17.833333333333332),
 (20153, 'HOH EDI', 'M'): (10.0, 19.166666666666668),
 (20153, 'HOH EDI', 'T'): (8.0, 17.833333333333332),
 (20153, 'HOH EDI', 'W'): (10.0, 19.166666666666668),
 (20153, 'HOH1', 'F'): (8.0, 17.0),
 (20153, 'HOH1', 'H'): (8.0, 21.833333333333332),
 (20153, 'HOH1', 'M'): (8.0, 21.5),
 (20153, 'HOH1', 'T'): (8.0, 21.833333333333332),
 (20153, 'HOH1', 'W'): (8.0, 21.5),
 (20153, 'HOH2', 'F'): (10.0, 13.333333333333334),
 (20153, 'HOH2', 'H'): (8.0, 19.833333333333332),
 (20153, 'HOH2', 'M'): (8.0, 17.833333333333332),
 (20153, 'HOH2', 'T'): (8.0, 19.833333333333332),
 (20153, 'HOH2', 'W'): (8.0, 17.833333333333332),
 (20153, 'HOH506', 'F'): (9.5, 16.833333333333332),
 (20153, 'HOH506', 'M'): (10.0, 13.0),
 (20153, 'HOH506', 'T'): (13.5, 16.333333333333332),
 (20153, 'HOH506', 'W'): (9.0, 16.0),
 (20153, 'HOH706', 'M'): (9.0, 11.833333333333334),
 (20153, 'HOH706', 'T'): (13.5, 16.333333333333332),
 (20153, 'HOH706', 'W'): (15.5, 21.5),
 (20153, 'JKP102', 'H'): (9.5, 21.5),
 (20153, 'JKP102', 'M'): (8.0, 21.5),
 (20153, 'JKP102', 'T'): (9.5, 21.5),
 (20153, 'JKP102', 'W'): (8.0, 21.5),
 (20153, 'JKP104', 'H'): (9.5, 21.5),
 (20153, 'JKP104', 'M'): (9.5, 21.5),
 (20153, 'JKP104', 'T'): (9.5, 21.5),
 (20153, 'JKP104', 'W'): (9.5, 21.5),
 (20153, 'JKP110', 'H'): (8.0, 21.5),
 (20153, 'JKP110', 'M'): (8.0, 21.5),
 (20153, 'JKP110', 'T'): (8.0, 21.5),
 (20153, 'JKP110', 'W'): (8.0, 21.5),
 (20153, 'JKP112', 'F'): (8.0, 14.666666666666666),
 (20153, 'JKP112', 'H'): (12.5, 21.5),
 (20153, 'JKP112', 'M'): (8.0, 21.5),
 (20153, 'JKP112', 'T'): (12.5, 21.5),
 (20153, 'JKP112', 'W'): (8.0, 21.5),
 (20153, 'JKP202', 'F'): (9.0, 12.0),
 (20153, 'JKP202', 'H'): (8.0, 21.5),
 (20153, 'JKP202', 'M'): (8.0, 21.5),
 (20153, 'JKP202', 'T'): (8.0, 21.5),
 (20153, 'JKP202', 'W'): (8.0, 21.5),
 (20153, 'JKP204', 'F'): (9.0, 16.0),
 (20153, 'JKP204', 'H'): (8.5, 21.5),
 (20153, 'JKP204', 'M'): (8.5, 21.5),
 (20153, 'JKP204', 'T'): (8.5, 21.5),
 (20153, 'JKP204', 'W'): (8.5, 21.5),
 (20153, 'JKP210', 'F'): (8.0, 14.666666666666666),
 (20153, 'JKP210', 'H'): (8.0, 21.5),
 (20153, 'JKP210', 'M'): (8.0, 22.0),
 (20153, 'JKP210', 'T'): (8.0, 21.5),
 (20153, 'JKP210', 'W'): (8.0, 22.0),
 (20153, 'JKP212', 'F'): (8.0, 14.666666666666666),
 (20153, 'JKP212', 'H'): (8.0, 21.5),
 (20153, 'JKP212', 'M'): (8.0, 21.5),
 (20153, 'JKP212', 'T'): (8.0, 21.5),
 (20153, 'JKP212', 'W'): (12.5, 21.5),
 (20161, 'ACC201', 'F'): (12.0, 13.833333333333334),
 (20161, 'ACC201', 'H'): (10.0, 19.833333333333332),
 (20161, 'ACC201', 'M'): (8.0, 19.833333333333332),
 (20161, 'ACC201', 'T'): (10.0, 19.833333333333332),
 (20161, 'ACC201', 'W'): (8.0, 19.833333333333332),
 (20161, 'ACC205', 'F'): (10.0, 16.833333333333332),
 (20161, 'ACC205', 'H'): (8.0, 17.833333333333332),
 (20161, 'ACC205', 'M'): (8.0, 21.5),
 (20161, 'ACC205', 'T'): (8.0, 19.833333333333332),
 (20161, 'ACC205', 'W'): (8.0, 21.5),
 (20161, 'ACC236', 'H'): (8.0, 21.5),
 (20161, 'ACC236', 'M'): (8.0, 21.5),
 (20161, 'ACC236', 'T'): (8.0, 20.833333333333332),
 (20161, 'ACC236', 'W'): (8.0, 21.5),
 (20161, 'ACC303', 'F'): (9.5, 12.833333333333334),
 (20161, 'ACC303', 'H'): (8.0, 19.833333333333332),
 (20161, 'ACC303', 'M'): (8.0, 21.333333333333332),
 (20161, 'ACC303', 'T'): (8.0, 19.833333333333332),
 (20161, 'ACC303', 'W'): (8.0, 21.5),
 (20161, 'ACC310', 'F'): (8.0, 15.833333333333334),
 (20161, 'ACC310', 'H'): (12.0, 17.833333333333332),
 (20161, 'ACC310', 'M'): (8.0, 19.833333333333332),
 (20161, 'ACC310', 'T'): (12.0, 21.5),
 (20161, 'ACC310', 'W'): (8.0, 19.833333333333332),
 (20161, 'ACC312', 'F'): (9.0, 11.0),
 (20161, 'ACC312', 'M'): (10.0, 16.5),
 (20161, 'ACC312', 'T'): (13.0, 16.0),
 (20161, 'ACC312', 'W'): (10.0, 11.833333333333334),
 (20161, 'BRI202', 'H'): (9.5, 20.5),
 (20161, 'BRI202', 'M'): (9.5, 21.5),
 (20161, 'BRI202', 'T'): (9.5, 21.5),
 (20161, 'BRI202', 'W'): (9.5, 21.5),
 (20161, 'BRI202A', 'F'): (10.0, 13.833333333333334),
 (20161, 'BRI202A', 'H'): (10.0, 17.833333333333332),
 (20161, 'BRI202A', 'M'): (10.0, 19.833333333333332),
 (20161, 'BRI202A', 'T'): (14.0, 17.833333333333332),
 (20161, 'BRI202A', 'W'): (10.0, 19.833333333333332),
 (20161, 'BRI5', 'F'): (10.0, 13.833333333333334),
 (20161, 'BRI5', 'H'): (10.0, 19.833333333333332),
 (20161, 'BRI5', 'M'): (8.0, 20.833333333333332),
 (20161, 'BRI5', 'T'): (10.0, 20.833333333333332),
 (20161, 'BRI5', 'W'): (8.0, 21.5),
 (20161, 'BRI8', 'F'): (8.0, 15.833333333333334),
 (20161, 'BRI8', 'H'): (8.0, 19.833333333333332),
 (20161, 'BRI8', 'M'): (8.0, 19.833333333333332),
 (20161, 'BRI8', 'T'): (8.0, 19.833333333333332),
 (20161, 'BRI8', 'W'): (8.0, 19.833333333333332),
 (20161, 'HOH EDI', 'F'): (10.0, 15.833333333333334),
 (20161, 'HOH EDI', 'H'): (8.0, 19.833333333333332),
 (20161, 'HOH EDI', 'M'): (10.0, 19.166666666666668),
 (20161, 'HOH EDI', 'T'): (8.0, 19.833333333333332),
 (20161, 'HOH EDI', 'W'): (10.0, 19.166666666666668),
 (20161, 'HOH1', 'F'): (12.0, 13.833333333333334),
 (20161, 'HOH1', 'H'): (8.0, 21.5),
 (20161, 'HOH1', 'M'): (8.0, 19.833333333333332),
 (20161, 'HOH1', 'T'): (8.0, 21.5),
 (20161, 'HOH1', 'W'): (8.0, 19.833333333333332),
 (20161, 'HOH2', 'F'): (10.0, 13.833333333333334),
 (20161, 'HOH2', 'H'): (8.0, 21.833333333333332),
 (20161, 'HOH2', 'M'): (8.0, 19.833333333333332),
 (20161, 'HOH2', 'T'): (8.0, 21.833333333333332),
 (20161, 'HOH2', 'W'): (8.0, 19.833333333333332),
 (20161, 'HOH506', 'F'): (10.5, 11.833333333333334),
 (20161, 'HOH506', 'H'): (13.0, 18.833333333333332),
 (20161, 'HOH506', 'M'): (13.5, 16.0),
 (20161, 'HOH506', 'T'): (9.0, 12.0),
 (20161, 'HOH506', 'W'): (10.0, 17.833333333333332),
 (20161, 'HOH706', 'F'): (12.5, 16.0),
 (20161, 'HOH706', 'H'): (12.0, 18.833333333333332),
 (20161, 'HOH706', 'M'): (15.0, 17.833333333333332),
 (20161, 'HOH706', 'T'): (11.5, 14.333333333333334),
 (20161, 'HOH706', 'W'): (11.5, 14.333333333333334),
 (20161, 'JKP102', 'H'): (9.5, 21.333333333333332),
 (20161, 'JKP102', 'M'): (9.5, 21.5),
 (20161, 'JKP102', 'T'): (9.5, 21.5),
 (20161, 'JKP102', 'W'): (9.5, 21.5),
 (20161, 'JKP104', 'F'): (9.0, 10.833333333333334),
 (20161, 'JKP104', 'H'): (9.5, 21.5),
 (20161, 'JKP104', 'M'): (10.0, 21.5),
 (20161, 'JKP104', 'T'): (9.5, 21.5),
 (20161, 'JKP104', 'W'): (10.0, 21.5),
 (20161, 'JKP110', 'H'): (10.0, 17.833333333333332),
 (20161, 'JKP110', 'M'): (8.0, 21.5),
 (20161, 'JKP110', 'T'): (10.0, 17.833333333333332),
 (20161, 'JKP110', 'W'): (8.0, 21.5),
 (20161, 'JKP112', 'F'): (13.0, 16.0),
 (20161, 'JKP112', 'H'): (8.0, 21.5),
 (20161, 'JKP112', 'M'): (8.0, 21.5),
 (20161, 'JKP112', 'T'): (8.0, 21.5),
 (20161, 'JKP112', 'W'): (8.0, 21.5),
 (20161, 'JKP202', 'H'): (9.5, 21.5),
 (20161, 'JKP202', 'M'): (8.0, 18.333333333333332),
 (20161, 'JKP202', 'T'): (9.5, 21.5),
 (20161, 'JKP202', 'W'): (8.0, 21.5),
 (20161, 'JKP204', 'H'): (8.5, 21.333333333333332),
 (20161, 'JKP204', 'M'): (8.25, 21.5),
 (20161, 'JKP204', 'T'): (8.5, 21.5),
 (20161, 'JKP204', 'W'): (8.25, 21.5),
 (20161, 'JKP210', 'H'): (8.0, 21.5),
 (20161, 'JKP210', 'M'): (9.5, 16.833333333333332),
 (20161, 'JKP210', 'T'): (8.0, 21.5),
 (20161, 'JKP210', 'W'): (9.5, 16.833333333333332),
 (20161, 'JKP212', 'F'): (8.0, 12.333333333333334),
 (20161, 'JKP212', 'H'): (8.0, 21.5),
 (20161, 'JKP212', 'M'): (8.0, 21.5),
 (20161, 'JKP212', 'T'): (8.0, 21.5),
 (20161, 'JKP212', 'W'): (8.0, 21.5),
 (20162, 'ACC201', 'H'): (9.0, 14.5),
 (20162, 'ACC201', 'M'): (12.0, 17.333333333333332),
 (20162, 'ACC201', 'T'): (9.0, 14.5),
 (20162, 'ACC201', 'W'): (12.0, 17.333333333333332),
 (20162, 'ACC303', 'H'): (9.0, 17.5),
 (20162, 'ACC303', 'M'): (9.0, 17.333333333333332),
 (20162, 'ACC303', 'T'): (9.0, 17.5),
 (20162, 'ACC303', 'W'): (9.0, 17.333333333333332),
 (20162, 'ACC310', 'H'): (9.0, 17.333333333333332),
 (20162, 'ACC310', 'M'): (9.0, 14.5),
 (20162, 'ACC310', 'T'): (9.0, 17.333333333333332),
 (20162, 'ACC310', 'W'): (9.0, 14.5),
 (20162, 'ACC312', 'M'): (9.0, 11.5),
 (20162, 'ACC312', 'T'): (15.0, 17.333333333333332),
 (20162, 'ACC312', 'W'): (9.0, 11.5),
 (20162, 'BRI202', 'H'): (18.0, 22.0),
 (20162, 'BRI202', 'M'): (9.0, 15.5),
 (20162, 'BRI202', 'W'): (9.0, 15.5),
 (20162, 'BRI202A', 'H'): (9.0, 11.5),
 (20162, 'BRI202A', 'T'): (9.0, 11.5),
 (20162, 'JKP102', 'H'): (12.0, 22.0),
 (20162, 'JKP102', 'M'): (9.0, 14.333333333333334),
 (20162, 'JKP102', 'T'): (12.0, 14.333333333333334),
 (20162, 'JKP102', 'W'): (9.0, 14.333333333333334),
 (20162, 'JKP104', 'H'): (13.5, 16.0),
 (20162, 'JKP104', 'M'): (9.0, 22.0),
 (20162, 'JKP104', 'T'): (13.5, 22.0),
 (20162, 'JKP104', 'W'): (9.0, 11.333333333333334),
 (20162, 'JKP110', 'F'): (8.833333333333334, 16.5),
 (20162, 'JKP110', 'M'): (18.0, 22.0),
 (20162, 'JKP110', 'T'): (18.0, 22.0),
 (20162, 'JKP110', 'W'): (18.0, 22.0),
 (20162, 'JKP112', 'H'): (18.0, 22.0),
 (20162, 'JKP112', 'M'): (18.0, 22.0),
 (20162, 'JKP112', 'T'): (18.0, 22.0),
 (20162, 'JKP112', 'W'): (18.0, 22.0),
 (20162, 'JKP202', 'H'): (18.0, 22.0),
 (20162, 'JKP202', 'M'): (18.0, 22.0),
 (20162, 'JKP202', 'T'): (18.0, 22.0),
 (20162, 'JKP202', 'W'): (18.0, 22.0),
 (20162, 'JKP204', 'H'): (9.0, 16.0),
 (20162, 'JKP204', 'M'): (13.0, 16.0),
 (20162, 'JKP204', 'T'): (9.0, 22.0),
 (20162, 'JKP204', 'W'): (13.0, 22.0),
 (20162, 'JKP210', 'F'): (8.0, 17.75),
 (20162, 'JKP210', 'H'): (8.0, 22.0),
 (20162, 'JKP210', 'M'): (8.0, 22.0),
 (20162, 'JKP210', 'T'): (8.0, 22.0),
 (20162, 'JKP210', 'W'): (8.0, 22.0),
 (20162, 'JKP212', 'H'): (9.0, 15.416666666666666),
 (20162, 'JKP212', 'M'): (9.0, 15.75),
 (20162, 'JKP212', 'T'): (9.0, 15.416666666666666),
 (20162, 'JKP212', 'W'): (9.0, 15.75),
 (20163, 'ACC201', 'H'): (10.0, 17.833333333333332),
 (20163, 'ACC201', 'M'): (10.0, 17.833333333333332),
 (20163, 'ACC201', 'T'): (10.0, 21.5),
 (20163, 'ACC201', 'W'): (10.0, 17.833333333333332),
 (20163, 'ACC205', 'H'): (10.0, 19.833333333333332),
 (20163, 'ACC205', 'M'): (10.0, 18.5),
 (20163, 'ACC205', 'T'): (10.0, 19.833333333333332),
 (20163, 'ACC205', 'W'): (10.0, 18.5),
 (20163, 'ACC236', 'H'): (8.0, 17.833333333333332),
 (20163, 'ACC236', 'M'): (8.0, 17.833333333333332),
 (20163, 'ACC236', 'T'): (8.0, 21.5),
 (20163, 'ACC236', 'W'): (8.0, 21.5),
 (20163, 'ACC303', 'H'): (8.0, 19.833333333333332),
 (20163, 'ACC303', 'M'): (10.0, 15.833333333333334),
 (20163, 'ACC303', 'T'): (8.0, 21.5),
 (20163, 'ACC303', 'W'): (10.0, 15.833333333333334),
 (20163, 'ACC310', 'H'): (10.0, 17.833333333333332),
 (20163, 'ACC310', 'M'): (16.0, 19.333333333333332),
 (20163, 'ACC310', 'T'): (10.0, 17.833333333333332),
 (20163, 'ACC312', 'F'): (13.0, 15.833333333333334),
 (20163, 'ACC312', 'H'): (9.0, 13.333333333333334),
 (20163, 'ACC312', 'M'): (14.0, 16.833333333333332),
 (20163, 'ACC312', 'T'): (12.0, 13.333333333333334),
 (20163, 'ACC312', 'W'): (9.5, 21.833333333333332),
 (20163, 'BRI202', 'F'): (13.0, 16.0),
 (20163, 'BRI202', 'H'): (12.5, 21.5),
 (20163, 'BRI202', 'M'): (15.5, 21.5),
 (20163, 'BRI202', 'T'): (12.5, 18.333333333333332),
 (20163, 'BRI202', 'W'): (17.0, 20.0),
 (20163, 'BRI202A', 'H'): (8.0, 17.833333333333332),
 (20163, 'BRI202A', 'M'): (10.0, 19.833333333333332),
 (20163, 'BRI202A', 'T'): (8.0, 19.833333333333332),
 (20163, 'BRI202A', 'W'): (10.0, 19.833333333333332),
 (20163, 'HOH EDI', 'F'): (10.0, 15.833333333333334),
 (20163, 'HOH EDI', 'H'): (8.0, 19.833333333333332),
 (20163, 'HOH EDI', 'M'): (8.0, 17.833333333333332),
 (20163, 'HOH EDI', 'T'): (8.0, 19.833333333333332),
 (20163, 'HOH EDI', 'W'): (8.0, 17.833333333333332),
 (20163, 'HOH1', 'H'): (10.0, 19.833333333333332),
 (20163, 'HOH1', 'M'): (8.0, 19.833333333333332),
 (20163, 'HOH1', 'T'): (10.0, 19.833333333333332),
 (20163, 'HOH1', 'W'): (8.0, 19.833333333333332),
 (20163, 'HOH2', 'F'): (8.0, 17.0),
 (20163, 'HOH2', 'H'): (8.0, 19.833333333333332),
 (20163, 'HOH2', 'M'): (8.0, 19.833333333333332),
 (20163, 'HOH2', 'T'): (8.0, 19.833333333333332),
 (20163, 'HOH2', 'W'): (8.0, 19.833333333333332),
 (20163, 'HOH506', 'F'): (14.0, 16.833333333333332),
 (20163, 'HOH506', 'M'): (10.0, 13.0),
 (20163, 'HOH506', 'T'): (13.5, 16.333333333333332),
 (20163, 'HOH506', 'W'): (13.0, 16.0),
 (20163, 'HOH706', 'F'): (9.5, 17.0),
 (20163, 'HOH706', 'H'): (13.0, 16.0),
 (20163, 'HOH706', 'T'): (13.5, 16.333333333333332),
 (20163, 'HOH706', 'W'): (14.0, 16.833333333333332),
 (20163, 'JFF LL101', 'H'): (8.0, 17.833333333333332),
 (20163, 'JFF LL101', 'M'): (10.0, 17.833333333333332),
 (20163, 'JFF LL101', 'T'): (8.0, 17.833333333333332),
 (20163, 'JFF LL101', 'W'): (10.0, 17.833333333333332),
 (20163, 'JFF LL102', 'H'): (8.0, 17.833333333333332),
 (20163, 'JFF LL102', 'M'): (8.0, 17.833333333333332),
 (20163, 'JFF LL102', 'T'): (8.0, 17.833333333333332),
 (20163, 'JFF LL102', 'W'): (8.0, 17.833333333333332),
 (20163, 'JFF LL103', 'H'): (10.0, 19.833333333333332),
 (20163, 'JFF LL103', 'M'): (8.0, 18.333333333333332),
 (20163, 'JFF LL103', 'T'): (10.0, 19.833333333333332),
 (20163, 'JFF LL103', 'W'): (8.0, 18.333333333333332),
 (20163, 'JFF LL105', 'F'): (10.0, 11.833333333333334),
 (20163, 'JFF LL105', 'H'): (8.0, 19.833333333333332),
 (20163, 'JFF LL105', 'M'): (8.0, 19.833333333333332),
 (20163, 'JFF LL105', 'T'): (8.0, 19.833333333333332),
 (20163, 'JFF LL105', 'W'): (8.0, 19.833333333333332),
 (20163, 'JFF LL125', 'F'): (10.0, 13.833333333333334),
 (20163, 'JFF LL125', 'H'): (8.0, 21.833333333333332),
 (20163, 'JFF LL125', 'M'): (8.0, 19.833333333333332),
 (20163, 'JFF LL125', 'T'): (8.0, 21.833333333333332),
 (20163, 'JFF LL125', 'W'): (8.0, 19.833333333333332),
 (20163, 'JFF233', 'H'): (8.0, 20.333333333333332),
 (20163, 'JFF233', 'M'): (9.5, 21.5),
 (20163, 'JFF233', 'T'): (8.0, 15.333333333333334),
 (20163, 'JFF233', 'W'): (9.5, 21.333333333333332),
 (20163, 'JFF236', 'H'): (10.0, 17.833333333333332),
 (20163, 'JFF236', 'M'): (10.0, 21.5),
 (20163, 'JFF236', 'T'): (10.0, 21.333333333333332),
 (20163, 'JFF236', 'W'): (10.0, 21.5),
 (20163, 'JFF239', 'F'): (8.0, 15.833333333333334),
 (20163, 'JFF239', 'H'): (8.0, 19.833333333333332),
 (20163, 'JFF239', 'M'): (8.0, 21.333333333333332),
 (20163, 'JFF239', 'T'): (8.0, 19.833333333333332),
 (20163, 'JFF239', 'W'): (8.0, 20.5),
 (20163, 'JFF240', 'F'): (9.5, 12.833333333333334),
 (20163, 'JFF240', 'H'): (10.0, 17.833333333333332),
 (20163, 'JFF240', 'M'): (10.0, 17.833333333333332),
 (20163, 'JFF240', 'T'): (10.0, 21.5),
 (20163, 'JFF240', 'W'): (10.0, 17.833333333333332),
 (20163, 'JFF241', 'F'): (10.0, 11.833333333333334),
 (20163, 'JFF241', 'H'): (10.0, 20.333333333333332),
 (20163, 'JFF241', 'M'): (10.0, 17.833333333333332),
 (20163, 'JFF241', 'T'): (10.0, 19.833333333333332),
 (20163, 'JFF241', 'W'): (10.0, 21.5),
 (20163, 'JFF312', 'F'): (8.0, 14.833333333333334),
 (20163, 'JFF312', 'H'): (8.0, 19.833333333333332),
 (20163, 'JFF312', 'M'): (8.0, 19.833333333333332),
 (20163, 'JFF312', 'T'): (8.0, 19.833333333333332),
 (20163, 'JFF312', 'W'): (8.0, 19.833333333333332),
 (20163, 'JFF313', 'F'): (8.0, 8.833333333333334),
 (20163, 'JFF313', 'H'): (8.0, 19.833333333333332),
 (20163, 'JFF313', 'M'): (8.0, 19.833333333333332),
 (20163, 'JFF313', 'T'): (8.0, 19.833333333333332),
 (20163, 'JFF313', 'W'): (8.0, 19.833333333333332),
 (20163, 'JFF316', 'F'): (10.0, 15.833333333333334),
 (20163, 'JFF316', 'H'): (12.0, 19.833333333333332),
 (20163, 'JFF316', 'M'): (10.0, 19.833333333333332),
 (20163, 'JFF316', 'T'): (10.0, 20.333333333333332),
 (20163, 'JFF316', 'W'): (10.0, 19.833333333333332),
 (20163, 'JFF322', 'F'): (10.0, 15.833333333333334),
 (20163, 'JFF322', 'H'): (10.0, 19.833333333333332),
 (20163, 'JFF322', 'M'): (10.0, 17.833333333333332),
 (20163, 'JFF322', 'T'): (10.0, 19.833333333333332),
 (20163, 'JFF322', 'W'): (10.0, 21.5),
 (20163, 'JFF327', 'H'): (8.0, 19.833333333333332),
 (20163, 'JFF327', 'M'): (10.0, 19.833333333333332),
 (20163, 'JFF327', 'T'): (8.0, 19.833333333333332),
 (20163, 'JFF327', 'W'): (10.0, 19.833333333333332),
 (20163, 'JFF328', 'F'): (10.0, 15.833333333333334),
 (20163, 'JFF328', 'H'): (8.0, 19.833333333333332),
 (20163, 'JFF328', 'M'): (8.0, 19.833333333333332),
 (20163, 'JFF328', 'T'): (8.0, 19.833333333333332),
 (20163, 'JFF328', 'W'): (8.0, 19.833333333333332),
 (20163, 'JFF331', 'H'): (8.0, 19.833333333333332),
 (20163, 'JFF331', 'M'): (8.0, 19.833333333333332),
 (20163, 'JFF331', 'T'): (8.0, 19.833333333333332),
 (20163, 'JFF331', 'W'): (8.0, 19.833333333333332),
 (20163, 'JFF414', 'H'): (10.0, 20.5),
 (20163, 'JFF414', 'M'): (8.0, 21.5),
 (20163, 'JFF414', 'T'): (10.0, 20.5),
 (20163, 'JFF414', 'W'): (8.0, 20.5),
 (20163, 'JFF416', 'H'): (10.0, 21.5),
 (20163, 'JFF416', 'M'): (8.0, 20.5),
 (20163, 'JFF416', 'T'): (10.0, 21.333333333333332),
 (20163, 'JFF416', 'W'): (8.0, 19.833333333333332),
 (20163, 'JFF417', 'H'): (9.333333333333334, 15.833333333333334),
 (20163, 'JFF417', 'M'): (9.333333333333334, 20.5),
 (20163, 'JFF417', 'T'): (9.333333333333334, 19.0),
 (20163, 'JFF417', 'W'): (9.333333333333334, 18.833333333333332),
 (20163, 'JKP102', 'H'): (8.0, 21.5),
 (20163, 'JKP102', 'M'): (9.5, 21.5),
 (20163, 'JKP102', 'T'): (8.0, 21.5),
 (20163, 'JKP102', 'W'): (9.5, 21.5),
 (20163, 'JKP104', 'H'): (9.5, 21.5),
 (20163, 'JKP104', 'M'): (9.5, 21.5),
 (20163, 'JKP104', 'T'): (9.5, 21.5),
 (20163, 'JKP104', 'W'): (9.5, 21.5),
 (20163, 'JKP110', 'H'): (8.0, 21.5),
 (20163, 'JKP110', 'M'): (9.5, 21.5),
 (20163, 'JKP110', 'T'): (8.0, 21.5),
 (20163, 'JKP110', 'W'): (9.5, 21.5),
 (20163, 'JKP112', 'H'): (12.5, 21.5),
 (20163, 'JKP112', 'M'): (12.5, 21.5),
 (20163, 'JKP112', 'T'): (12.5, 21.5),
 (20163, 'JKP112', 'W'): (12.5, 21.5),
 (20163, 'JKP202', 'H'): (9.5, 21.5),
 (20163, 'JKP202', 'M'): (9.5, 21.5),
 (20163, 'JKP202', 'T'): (9.5, 21.5),

# Code Demonstration: Dumping Data Back into a DataFrame

In [19]:
lines=[]
for term,room,day in ans:
    beg,end=ans[term,room,day]
    lines.append([term,room,day,beg,end])
output=pd.DataFrame(lines,columns=['Term','Room','Day','Earliest','Latest'])

output.to_csv('Room_Simple_Usage.csv')
output.info()
output.describe()
output.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 687 entries, 0 to 686
Data columns (total 5 columns):
Term        687 non-null int64
Room        687 non-null object
Day         687 non-null object
Earliest    687 non-null float64
Latest      687 non-null float64
dtypes: float64(2), int64(1), object(2)
memory usage: 26.9+ KB

    Term     Room Day  Earliest     Latest
0  20153   ACC303   M       8.0  19.833333
1  20153   ACC303   W       8.0  19.833333
2  20153   ACC303   T       8.0  21.500000
3  20153   ACC303   H       8.0  21.833333
4  20153  HOH EDI   F      10.0  15.833333
5  20153   ACC310   T       8.0  17.833333
6  20153   ACC310   H       8.0  17.833333
7  20153   ACC310   M       8.0  21.500000
8  20153   ACC310   W       8.0  17.833333
9  20153   ACC205   M      10.0  21.500000

# Module 3: Developing an Algorithm to Compute a Non-Trivial Metric

## Exercse 3: 
Complete the following code to compute the total usage within prime time

In [ ]:
primeStart=10
primeEnd=16
sortedList=[(8,10),(10.5,11.5),(11,12),(14,17),(18,20)]
usage=0
prev=0
for start,end in sortedList:
    # Complete your code here
    
print('Total usage within prime time',usage)
print('Proportion of prime time used',usage/(primeEnd-primeStart))

In [46]:
# Expected output

Total usage within prime time 3.5
% of prime time used 0.5833333333333334

# Putting it all together

Create code that outputs a file for each term, room, and day the percentage of prime time used.

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

primeStart=10
primeEnd=16
schedule=pd.read_excel('Marshall_Course_Enrollment_1516_1617.xlsx')
cancelled=pd.read_excel('Cancelled_Courses_1516_1617.xlsx')
master=schedule.append(cancelled)
capacities=pd.read_excel('Marshall_Room_Capacity_Chart.xlsx')



def convert(inputTime):
    #Complete code from challenge 1

roomSet=set(capacities.Room)
ans={}


def loadDataDict(df,roomSet):
    # Complete your code here from modification of challenge 2

    return ans
                    
def computeUsage(inputList, primeStart,primeEnd):
    # Complete your code here from challenge 3

lines=[]
for term,room,day in loadDataDict(master,roomSet):
    lines.append([term,room,day,computeUtilization(ans[term,room,day],primeStart,primeEnd)])

output=pd.DataFrame(lines,columns=['Term','Room','Day','Utilization'])
output.to_csv('RoomUsage.csv')
output.head()

    Term     Room Day  Utilization
0  20153   ACC303   M     0.583333
1  20153   ACC303   W     0.583333
2  20153   ACC303   T     0.583333
3  20153   ACC303   H     0.583333
4  20153  HOH EDI   F     0.555556

In [56]:
# Expected output

    Term     Room Day  Utilization
0  20153   ACC303   M     0.583333
1  20153   ACC303   W     0.583333
2  20153   ACC303   T     0.583333
3  20153   ACC303   H     0.583333
4  20153  HOH EDI   F     0.555556